plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

packageExtensions:
  fastify-cors@*:
    dependencies:
      fastify: "^3.20.2"
  middie@*:
    dependencies:
      fastify: "^3.20.2"
  '@nestjs/platform-fastify@*':
    dependencies:
      fastify-static: "^2.7.0"
      point-of-view: "^4.15.2"

yarnPath: .yarn/releases/yarn-3.0.0-rc.5.cjs
