version: "3.7"

services:
  nginx_app:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./packages/fastify-app/static/index.html:/data/www/index.html
      - ./packages/fastify-app/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server

  server:
    image: node:16-alpine
    working_dir: /server
    volumes:
      - ./:/server
    entrypoint: yarn workspace @packages/fastify-app start
    expose:
      - 3000
    ports:
      - "3000:3000"
    environment:
      MODE: DEV
      PORT: 3000
