version: '3.7'

services:

  db:
    image: postgres
    restart: always
    env_file:
      - docker.env
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

#  mongo:
#    image: mongo:latest
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
#      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
#    ports:
#      - '27017:27017'
